### ISSUE TITLE
Slippipedia Crashes When Analyzing

### ISSUE THREAD

**Issue by DMenton** [cbartsch/Slippipedia#10]
Whenever I try and analyze the some sets, the window closes. This has not been a problem for me in the past, but I'm not sure what the issue is. I am on PC btw.

**Comment by cbartsch** [comment]
Does it crash consistently at a specific replay, or generally after X number of analyzed replays?

**Comment by cbartsch** [comment]
@SpeeedySloth please re-test with Slippipedia v1.1 and report more details if it still happens.

**Comment by cbartsch** [comment]
Closed for now because it might be fixed by v1.1. Re-open if it persists
