### ISSUE TITLE
Doubles Data Skews Stats

### ISSUE THREAD

**Issue by xNocki** [cbartsch/Slippipedia#11]
I play doubles very often on slippi, and have done so since the beta for doubles was available. 
The issue is that slippi replays display doubles games as me vs my teammate, or me vs only one other player when the data from the match itself displays different information. The easiest example I can provide of this is I am positive that I have played a total of 20 or fewer falco games (I'm a Peach main, really not good with Falco), and yet the top chars used overview displays 223 falco games.
![image](https://user-images.githubusercontent.com/12977033/120407126-5b5ae800-c301-11eb-8b18-49cff8f08536.png)

This can be seen in the Players tab where it thinks I am playing against Nocki (which is my tag). 
![image](https://user-images.githubusercontent.com/12977033/120407345-d3c1a900-c301-11eb-8616-b0c3f219290f.png)
![image](https://user-images.githubusercontent.com/12977033/120407374-e4721f00-c301-11eb-9cb6-9bc9ea902d94.png)

Hope this is enough information to make some adjustments around this. It seems like an awesome tool and I think it will help provide some data driven people (like myself) good match ups to work on and things to look at!

**Comment by xNocki** [comment]
Update: I'm now aware you can filter so that I'm the only player seen. I think that gets rid of some of the information around doubles games though, as they don't always display as me vs someone.

**Comment by cbartsch** [comment]
@xNocki that doesn't make too much sense to me because Slippipedia does not read doubles games at all, they are skipped during analysis.

Could you check again if that is the actual problem? Otherwise, please upload a replay so I can test it myself.

**Comment by cbartsch** [comment]
@xNocki closing until further info. Doubles matches are not analyzed or stored at all by Slippipedia.
