### ISSUE TITLE
The desktop app isn't recognized.

### ISSUE THREAD

**Issue by mogaku9** [cbartsch/Slippipedia#12]
I selected the folder in which the app is located, yet it repeats that it's not found, what do I do?

**Comment by cbartsch** [comment]
As discussed on Discord, this needs the Slippi Desktop App, download it here: https://slippi.gg/downloads

![image](https://user-images.githubusercontent.com/3541682/120869368-9b86c880-c596-11eb-9cf6-4347cb2c424a.png)

Select the folder where the replay dolphin is located, which is usually `C:\Users\<username>\AppData\Roaming\Slippi Desktop App`

**Comment by mogaku9** [comment]
I have the desktop app, yet it still won't recognize it.

**Comment by cbartsch** [comment]
Should be fixed in next version. There is now an option to reset the path to the default value.

Please let me know if this fixes your problem. (update soon)

![image](https://user-images.githubusercontent.com/3541682/128466773-448dd481-39a1-40bf-aee9-a0212ed848c1.png)
