### ISSUE TITLE
Console Replay Features

### ISSUE THREAD

**Issue by Surippi** [cbartsch/Slippipedia#13]
Would be nice to be able to filter players by port position given console replays don't have tag data etc.
[Console Replays.zip](https://github.com/cbartsch/Slippipedia/files/6618618/Console.Replays.zip)

**Comment by cbartsch** [comment]
Next version will include option to filter by player port number.

![image](https://user-images.githubusercontent.com/3541682/128475666-9edeaede-b61f-4f7a-a813-ebb8063269da.png)

It also displays console games better.

![image](https://user-images.githubusercontent.com/3541682/128475714-93ff4370-ee05-46c3-93a3-6ee747e9c6b7.png)
