### ISSUE TITLE
Slippipedia partially merging a recent session with one from a while ago

### ISSUE THREAD

**Issue by WoblPika** [cbartsch/Slippipedia#15]
![mang5](https://user-images.githubusercontent.com/87900904/126868141-76b792d0-5722-4e3e-a974-4f8795ad4842.png)
This one is pretty self explanatory, I played Weston today in one game then I went on slippipedia but it seems like it somehow got counted with a session from a few days ago which made it display a 25% win rate (and a Marth icon as I played Marth vs him those few days ago) as I won the one game we played today however it still only displays the stock counts for the one game like it should.
Never seen this issue before.

**Comment by cbartsch** [comment]
Currently all games vs the same opponent are always merged into a "session". 

Might add a time limit e.g. new session starts if no games for 1 hour or something.

**Comment by cbartsch** [comment]
Will be fixed in next version. Please report afterwards if still buggy (will be released soon)
