### ISSUE TITLE
Adding Favorites to SPD?

### ISSUE THREAD

**Issue by SukeSJ** [cbartsch/Slippipedia#16]
Maybe it could be possible to add a favorites tab to SPD? Just a simple ☆ next to the replays where the "Show in Folder" and "Open Replay File" is and a TAB at the bottom with favorites?

Could be nice for people who wanna analyze a match they had for later

**Comment by cbartsch** [comment]
Feature will be included in next update :)

![image](https://user-images.githubusercontent.com/3541682/128446569-48684792-7487-4793-8eba-8fdb0b01d2c0.png)
