### ISSUE TITLE
Slippipedia cant find the Slippi Launcher

### ISSUE THREAD

**Issue by Nifaso** [cbartsch/Slippipedia#17]
I installed the new version and it asked me to select the location of the Slippi Launcher and I put it in but the folder didn't show it in it even though it was, I linked it anyways a couple of times and it didn't recognize it was there at all. IDK what to do

I attached a picture of the problems I encountered as well as one of the slippipedia files I have. 

![slippipedia](https://user-images.githubusercontent.com/90467301/132880258-969a0b9e-0d27-440d-83db-d53b9a4ac734.png)

![files](https://user-images.githubusercontent.com/90467301/132880792-1384a76a-02d0-431c-ac41-9e9971c4e52e.png)

Please let me know if im messing up on my end so I can fix it

**Comment by cbartsch** [comment]
This is a bit tricky, you need to select the Slippi Launcher's app data folder and not the folder where it's installed.

The folder is like `C:\Users\<username>\AppData\Roaming\Slippi Launcher`

However it is usually possible to have Slippipedia auto-detect that. Try using the "Reset to default" option:
![image](https://user-images.githubusercontent.com/3541682/133050037-e77e529c-9d05-48ae-9dd0-ccebf99832a4.png)

**Comment by cbartsch** [comment]
Closed for now because more info needed if still existing. Re-open if yes
