### ISSUE TITLE
Replay browser not populating despite having matching analyzed replays.

### ISSUE THREAD

**Issue by ShlizCode** [cbartsch/Slippipedia#18]
Today I updated to the 1.1 windows release of slippipedia, and when browsing the replays and punishes windows, slippipedia reports the correct number of matching replays, but the window does not populate with the matching replays or punishes

Here is a screenshot of the replay browser: 

![replays_not_loading](https://user-images.githubusercontent.com/91035715/133946249-01990654-bbe4-4a49-a7d3-873b055e7f19.png)

Here is a screenshot of the punish browser:

![punishes_not_loading](https://user-images.githubusercontent.com/91035715/133946295-87844d0a-32e8-4f1a-a55b-a792191babd4.png)

Here is a confirmation that the replays have been analyzed:

![replays_stored](https://user-images.githubusercontent.com/91035715/133946253-3c9c590b-9578-4f13-9e61-36427961404e.png)

All of the other statistical analysis (matchups, stages played on, etc.) seems to work properly.

Any insight or guidancce would be greatly appreciated!
.

**Comment by ShlizCode** [comment]
Update: When re-launching slippepedia 1.0-rc3, I am presented with this notification on the setup screen:

![Database_Version_Outdated](https://user-images.githubusercontent.com/91035715/133946581-606bb968-c02f-42ad-97f7-7dcc57f4c544.png)

Should this also be appearing in version 1.1?

**Comment by ShlizCode** [comment]
Another quick update: After clearing and re-analyzing the replay files, the replay browser works fine. Leaving this issue just because it seems like the message that I got in version 1.0-rc3 should have shown up in version 1.1, but I wouldn't be offended if somebody else decided this issue can be closed. 

Also just want to say I'm very impressed with the improvements to the setup page! Replays analyze way faster and the progress bar works a lot better. Great work!

**Comment by cbartsch** [comment]
Thanks for this report. Looks like there's a problem loading the replay list after updating.

Since you already cleared the database it's hard to debug what went wrong, so I'll leave this issue open in case someone else experiences the bug.

> Update: When re-launching slippepedia 1.0-rc3, I am presented with this notification on the setup screen:

This shows because when using v1.1 for the first time, the database updates itself automatically to v2.2. But there is no automatic downgrade as you're not expected to use 1.0 again.

Maybe something went wrong in that automatic upgrade for your database. If it happens again, please send me the database file (it's under the AppData location).

**Comment by cbartsch** [comment]
Closed for maybe being a singular case or fixed in newer version already. Re-open if it persists

**Comment by ShlizCode** [comment]
Hey Cbartsch,

Just saw you closed out the issue I reported, and I wanted to thank you for
all the hard work you put in on slippipedia! It’s an incredible application
and I use it all the time, more often than the actual slippi replay browser.

Keep up the great work!

Thanks,
Shlizark

**Comment by cbartsch** [comment]
@ShlizCode thank you for the nice words! Finally found some time and motivation to keep improvig it again :)

If you want to support me for free, I'd appreciate a social media follow ([Twitter](https://twitter.com/ChrisuSSBMtG), [Twitch](https://www.twitch.tv/chrisuan))

(Or buy me a beer at [Patreon](https://www.patreon.com/chrisu) ;) )
