### ISSUE TITLE
Green Yoshi Icon being displayed wrong but not always

### ISSUE THREAD

**Issue by WoblPika** [cbartsch/Slippipedia#29]
Okay so this is a weird situation, about a week ago or so I played tournament sets vs TheDerp, a Green Yoshi and while checking my games vs Yoshi I noticed that green yoshi is being displayed as half a donkey kong stock, but it's not consistent in the sense that I have other games vs green yoshi where this does not happen. 
![1](https://user-images.githubusercontent.com/87900904/197886005-6a8166c8-f018-47f2-8b50-a06bee19ca3f.png)
![2](https://user-images.githubusercontent.com/87900904/197886008-20e7063c-573a-4890-a294-6bfba314cadd.png)
[a.zip](https://github.com/cbartsch/Slippipedia/files/9864226/a.zip)

**Comment by cbartsch** [comment]
Thanks for the report, fixed in 703a6fc
