### ISSUE TITLE
'Show statistics for games' button in browser not working

### ISSUE THREAD

**Issue by s351929** [cbartsch/Slippipedia#3]
Steps to reproduce:
1. Navigate to browser on Windows
2. Find any set of games
3. Press the 'Show statistics for games'

What happens:
Nothing happens, the button flashes

Expected behaviour:
Show a stats screen for the group of games.

Platform: Windows

**Comment by cbartsch** [comment]
Thank you for the report. Fixed in new version 1.0-release. https://github.com/cbartsch/Slippipedia/releases/tag/1.0-release
