### ISSUE TITLE
clip not getting saved

### ISSUE THREAD

**Issue by WoblPika** [cbartsch/Slippipedia#30]
For example I want to clip a combo so I play the punish, then when it ends I close the replay dolphin, slippipedia of course asks me if I want to save it or not. On Setup it tells me the video was indeed saved but it's nowhere to be found, I also noticed there is no progress bar like there usually was when saving videos so effectively nothing is happening for some reason.  
Dunno if it helps but it does seem like the audio and video are getting dumped, then I guess nothing is happening? idk
![image](https://user-images.githubusercontent.com/87900904/200699576-d5d4571e-cbac-442b-9bf6-d9ca21519585.png)
I don't think I installed ffmpeg wrong either as all I did was replace the old slippipedia files with the new ones upon switching to official 2.0

**Comment by c-bartsch** [comment]
Is anything included in the dump-2022... folder?

This sounds like a bug that was fixed soon after 2.0 release, please try re-downloading 2.0, if the bug goes away then.

If not, please attach the log.txt file from the Slippipedia folder.

**Comment by WoblPika** [comment]
hey that worked, forgot about this for a while lmao
consider it closed

**Comment by WoblPika** [comment]
hey that worked, forgot about this for a while lmao
consider it closed
