### ISSUE TITLE
Option to remove smooth scrolling

### ISSUE THREAD

**Issue by ShanaryS** [cbartsch/Slippipedia#32]
It is impossible to navigate games in the browser.

**Comment by cbartsch** [comment]
Hi @ShanaryS I improved the scrolling in Version 2.1, can you check if the issue is resolved?

If not, please be more specific what the problem is.

**Comment by ShanaryS** [comment]
It's fixed now thanks! The issue was that using the scroll wheel would cause it to keep scrolling even after the scroll wheel has stopped. Making it very hard to precisely move around.

**Comment by cbartsch** [comment]
Good to hear!
