### ISSUE TITLE
Filter by length of punish

### ISSUE THREAD

**Issue by 21jujubees** [cbartsch/Slippipedia#33]
I'd like if there was a way to filter punishes by how long they take, so that I can cut out the 20+ second edgeguard sequences from the search results. Some filter like every punish under X seconds gets shown could work.

**Comment by cbartsch** [comment]
Fixed in version 2.1 (to be released hopefully today)

![image](https://github.com/cbartsch/Slippipedia/assets/3541682/bdb235a7-94b8-4443-85dd-14a136d5dcfa)
