### ISSUE TITLE
Allow favouriting of .slp file from Punish screen

### ISSUE THREAD

**Issue by ghost** [cbartsch/Slippipedia#34]
Currently you can favourite games from the 'Games' browser screen, but you cannot from the 'Punish' browser screen. Would be helpful to be able to favourite games that contain punishes/combos to be able to come back and record.

**Comment by c-bartsch** [comment]
This is a bug in the current release version, it is fixed in the next update. Will post here when it's released.

**Comment by cbartsch** [comment]
Fixed in Version 2.1
