### ISSUE TITLE
Setup analyze getting stuck on certain replays

### ISSUE THREAD

**Issue by NeilHarbin0** [cbartsch/Slippipedia#4]
Certain replays can cause the analysis in the setup tab to become stuck until you press cancel.

Here is one such replay that causes it to become stuck.
https://drive.google.com/file/d/1wBZ-EOXe7nFo6opuOB2vgGjERANbgUWj/view?usp=sharing

Possible remedy: Add a timeout for individual parses, so that if it does not return after X number of seconds, it will move on.

**Comment by cbartsch** [comment]
Note: Probably doubles matches, those are not supported at all.

-> add better error handling for those

**Comment by NeilHarbin0** [comment]
> 
> 
> Note: Probably doubles matches, those are not supported at all.
> 
> -> add better error handling for those

The replay file I provided is a singles game vs a Sheik that killed themselves several times. Doubles games in my experience are just skipped, and not added to the database. They don't cause the analysis to get stuck like this one game does.

**Comment by cbartsch** [comment]
Thank for the report. This specific bug is fixed in the next version (builds coming soon).

Please also report new bugs if you encounter them after updating.
