### ISSUE TITLE
Date range can't be manually modified

### ISSUE THREAD

**Issue by NeilHarbin0** [cbartsch/Slippipedia#5]
Date range selection doesn't seem to be modifiable manually. After selecting Last 365 days, I manually changed the date, but the filter doesn't get updated after hitting enter/leaving the cell/or selecting other non-date filter options.

![Date manual](https://user-images.githubusercontent.com/10625224/120262056-2d28ca00-c267-11eb-9b05-3288e553a037.gif)

The filter just doesn't update, it only works with the preset buttons. One thing odd might be that the date format looks different between the manual entry boxes and the filter box. (5/31/2020 11:03 PM vs 31/5/2020 23:03)

I did also try entering the format as it appears in the filter box, but that also didn't work.

**Comment by cbartsch** [comment]
It should work actually, try inputting the month in the date as 03 instead of 3. Will add better validation though.

**Comment by NeilHarbin0** [comment]
Padding with a 0 doesn't seem to work either. I have tried changing the year too. I also tried changing the month and day to be 12 or lower so it would work even if it was detecting them in reverse. I tried removing the PM/AM to look like it appears in the filter box. None of these things work for me.

**Comment by cbartsch** [comment]
This issue was due to a bug which made the date not show up in the text box in the desired format.

Will be fixed in the next version. In the meantime, you can manually input the date in the format `dd/MM/yyyy HH:mm` - e.g. `05/08/2021 11:03` (leading zeroes + 24h time with no AM/PM)
