### ISSUE TITLE
Certain replay is detecting opponents airdodges as 4.2Billion

### ISSUE THREAD

**Issue by NeilHarbin0** [cbartsch/Slippipedia#7]
This specific replay shows normally in Slippi desktop app with the opponent airdodging 0 times. Slippipedia shows unsigned integer max value instead.

https://drive.google.com/file/d/1k8i4O2OWcZJDLx7FLYPByBsdDmhwxhkr/view?usp=sharing

**Comment by cbartsch** [comment]
Thank you for the report, it was caused by a bug in the slippc library
